version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01

    working_directory: ~/template

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: npm run build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Clone dist
          working_directory: ~/template/dist
          command: |
            git clone --depth 1 https://${GP_GH_TOKEN}@github.com/yswor/yswor.github.io.git

      - deploy:
          name: Trigger deployment
          working_directory: ~/template/dist
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "heichatutu@gmail.com"
            git config user.name "Deployment Bot"
            git commit --allow-empty -m "deploy"
            # Push quietly to prevent showing the token in log
            git push -q https://${GP_GH_TOKEN}@github.com/yswor/yswor.github.io.git master
